name: sa-mtp
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - ca-certificates=2025.8.3=h4c7d964_0
  - libsqlite=3.50.4=hf5d6505_0
  - openssl=3.5.2=h725018a_0
  - pip=22.1.2=pyhd8ed1ab_0
  - python=3.7.12=h900ac77_100_cpython
  - python_abi=3.7=4_cp37m
  - setuptools=65.3.0=py37h03978a9_0
  - sqlite=3.50.4=hdb435a2_0
  - ucrt=10.0.22621.0=h57928b3_1
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - vs2015_runtime=14.44.35208=h38c0c73_31
  - wheel=0.41.3=pyhd8ed1ab_0
  - pip:
      - absl-py==1.2.0
      - astor==0.8.1
      - certifi==2022.9.14
      - charset-normalizer==2.1.1
      - colorama==0.4.6
      - cycler==0.11.0
      - docopt==0.6.2
      - fair-esm==2.0.0
      - filelock==3.12.2
      - fonttools==4.38.0
      - fsspec==2023.1.0
      - gast==0.5.3
      - google-pasta==0.2.0
      - googledrivedownloader==0.4
      - grpcio==1.48.1
      - h5py==3.7.0
      - huggingface-hub==0.16.4
      - idna==3.4
      - importlib-metadata==4.12.0
      - isodate==0.6.1
      - jinja2==3.1.2
      - joblib==1.2.0
      - keras-applications==1.0.8
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.5
      - markdown==3.4.1
      - markupsafe==2.1.1
      - matplotlib==3.5.3
      - networkx==2.6.3
      - numpy==1.21.6
      - packaging==24.0
      - pandas==1.3.5
      - pillow==9.2.0
      - pipreqs==0.4.11
      - protobuf==3.20.1
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - python-louvain==0.16
      - pytz==2022.2.1
      - pyyaml==6.0
      - rdflib==6.2.0
      - regex==2024.4.16
      - requests==2.28.1
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - seaborn==0.11.2
      - six==1.16.0
      - tensorboard==1.14.0
      - tensorboardx==2.5.1
      - tensorflow==1.14.0
      - tensorflow-estimator==1.14.0
      - termcolor==2.0.1
      - threadpoolctl==3.1.0
      - tokenizers==0.13.3
      - torch==1.11.0
      - torchaudio==0.11.0
      - torchvision==0.12.0
      - tqdm==4.64.1
      - transformers==4.25.1
      - typing-extensions==4.3.0
      - urllib3==1.26.12
      - werkzeug==2.2.2
      - wrapt==1.14.1
      - yarg==0.1.9
      - zipp==3.8.1
